name: Minor C/C++ CI

on:
  push:
    branches-ignore:
      - 'ignore*'
      - 'temp*'
      - master
    paths-ignore:
      - 'images/*'
  pull_request:
    paths-ignore:
      - 'images/*'
    branches-ignore:
      - master

jobs:
  linux:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        MAKE:
          - make -j9 SANITIZE=1 LONG=1
          - make -j9 CC=gcc\ -std=c99
          - make -j9 CC=gcc\ -std=c11
          - make examples SANITIZE=1
    steps:
    - uses: actions/checkout@v2
    - run:  ${{ matrix.MAKE }}
