name: Minor C/C++ CI

on:
  push:
    branches-ignore:
      - 'ignore*'
      - 'temp*'
      - master
    paths-ignore:
      - 'images/*'
  pull_request:
    paths-ignore:
      - 'images/*'
    branches-ignore:
      - master

jobs:
  linux:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        MAKE:
          - make -j4 SANITIZE=1
          - make -j4 CC='gcc -std=c99'
          - make -j4 CC='gcc -std=c11'
          - make -j4 CXX='clang++ -std=c++2a -stdlib=libc++'
          - make examples SANITIZE=1
          - make perf
    steps:
    - uses: actions/checkout@v2
    - run:  ${{ matrix.MAKE }}
  windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1
    - uses: ilammy/msvc-dev-cmd@v1
    - run:  nmake -f Makefile.win
  macOS:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - run:  make CXX='c++ -std=c++2a'
