name: Minor C/C++ CI

on:
  push:
    branches-ignore:
      - 'ignore*'
      - 'temp*'
      - master
    paths-ignore:
      - 'images/*'
  pull_request:
    paths-ignore:
      - 'images/*'
    branches-ignore:
      - master

jobs:
  linux:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        MAKE:
          - make -j4 SANITIZE=1
          - make -j4 CC='gcc -std=c99'
          - make -j4 CC='gcc -std=c11'
          # TODO fails with -std=c++2a and c++17 on vec capacity
          - make -j4 CXX='clang++ -std=c++11 -stdlib=libc++'
          - make examples SANITIZE=1
          - make perf
    steps:
    - uses: actions/checkout@v2
    - run:  ${{ matrix.MAKE }}
